# Introducción.

En el ejemplo anterior nos percatamos que cuando la acción que se realiza en un cuaderno depende del usuario, existe la posibilidad que el usuario introduzca un valor que rompa nuestro código.

En ese sentido, el objetivo de este cuaderno es el de capturar los posibles errores para que el código no se rompa.

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
def bisiesto(n):

    result = []

    if n % 400 == 0:
        secular = True
        bisiesto = True
    elif n % 100 == 0:
        secular = False
        bisiesto = False
    elif n % 4 == 0:
        secular = False
        bisiesto = True
    else:
        secular = False
        bisiesto = False

    if n % 100 == 0:
        mult100 = True
    else:
        mult100 = False

    if n % 4 ==0:
        mult4 = True
    else:
        mult4 = False

    result.append(n)
    result.append(bisiesto)
    result.append(secular)
    result.append(mult100)
    result.append(mult4)

    return result

In [3]:
def diasemana(n):

    a=np.remainder(1+5*np.remainder((n-1),4)+4*np.remainder((n-1),100)+6*np.remainder((n-1),400),7)

    if a == 0:
        dia = "domingo"
    elif a == 1:
        dia = "lunes"
    elif a == 2:
        dia = "martes"
    elif a == 3:
        dia = "miércoles"
    elif a == 4:
        dia = "jueves"
    elif a == 5:
        dia = "viernes"
    else:
        dia = "sábado"

    return dia

In [4]:
df = pd.DataFrame()

años = []
dias = []

for i in range(1, 3001):
    bis = bisiesto(i)
    day = diasemana(i)

    años.append(bis)
    dias.append(day)

df = pd.DataFrame(años, columns=['Año', 'Bisiesto', 'Secular', 'Múltiplo_100', 'Múltiplo_4'])
df['Comienza en'] = dias
df = df.reindex(columns=['Año', 'Comienza en', 'Bisiesto', 'Secular', 'Múltiplo_100', 'Múltiplo_4'])
df

       Año Comienza en  Bisiesto  Secular  Múltiplo_100  Múltiplo_4
0        1       lunes     False    False         False       False
1        2      martes     False    False         False       False
2        3   miércoles     False    False         False       False
3        4      jueves      True    False         False        True
4        5      sábado     False    False         False       False
...    ...         ...       ...      ...           ...         ...
2995  2996     viernes      True    False         False        True
2996  2997     domingo     False    False         False       False
2997  2998       lunes     False    False         False       False
2998  2999      martes     False    False         False       False
2999  3000   miércoles     False    False          True        True

[3000 rows x 6 columns]

In [5]:
X = df[['Año', 'Secular', 'Múltiplo_100', 'Múltiplo_4']]
Y = df[['Bisiesto']]

print(X)
print(Y)

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

logisticregression = LogisticRegression()

logisticregression.fit(x_train, y_train.values.ravel())

predictions = logisticregression.predict(x_test)
score = logisticregression.score(x_test, y_test)
params = logisticregression.get_params(deep=True)

print(score)

       Año  Secular  Múltiplo_100  Múltiplo_4
0        1    False         False       False
1        2    False         False       False
2        3    False         False       False
3        4    False         False        True
4        5    False         False       False
...    ...      ...           ...         ...
2995  2996    False         False        True
2996  2997    False         False       False
2997  2998    False         False       False
2998  2999    False         False       False
2999  3000    False          True        True

[3000 rows x 4 columns]
      Bisiesto
0        False
1        False
2        False
3         True
4        False
...        ...
2995      True
2996     False
2997     False
2998     False
2999     False

[3000 rows x 1 columns]
1.0

In [10]:
while True:
  try:
    year_input = input("Entre el Año: ")
    year = int(year_input)
    break
  except ValueError:
    print("Oops! No es válido. Intente nuevamente...")

año = []

bisi = bisiesto(year)
año.append(bisi)

df1 = pd.DataFrame()
df1 = pd.DataFrame(año, columns=['Año', 'Bisiesto', 'Secular', 'Múltiplo_100', 'Múltiplo_4'])

X1 = df1[['Año', 'Secular', 'Múltiplo_100', 'Múltiplo_4']]
resultado = logisticregression.predict(X1)

d = diasemana(year)

if resultado == True:
    print(year, "es un año bisiesto y comienza en", d)
else:
    print(year, "no es un año bisiesto y comienza en", d)

Oops! No es válido. Intente nuevamente...
655565565655656565 es un año bisiesto y comienza en martes

In [6]:
def es_bisiesto(a):
    return a % 400 == 0 or (a % 4 == 0 and a % 100 != 0)

def zeller(dia, mes, anio):
    if mes < 3:
        mes = mes + 12
        anio = anio - 1
    K = anio % 100    # últimos dos dígitos
    J = anio // 100   # siglo
    suma = dia + (13 * (mes + 1)) // 5 + K + K // 4 + J // 4 + 5 * J
    return suma, suma % 7

dias_semana = ["sábado", "domingo", "lunes", "martes", "miércoles", "jueves", "viernes"]
dias_mes = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

In [7]:
filas = []
for anio in range(1900, 2101):
    for mes in range(1, 13):
        ultimo = dias_mes[mes - 1]
        if mes == 2 and es_bisiesto(anio):
            ultimo = 29
        for dia in range(1, ultimo + 1):
            suma, h = zeller(dia, mes, anio)
            filas.append([dia, mes, anio, suma, dias_semana[h]])

df = pd.DataFrame(filas, columns=['Día', 'Mes', 'Año', 'Suma', 'Día_semana'])
df

       Día  Mes   Año  Suma Día_semana
0        1    1  1900   254      lunes
1        2    1  1900   255     martes
2        3    1  1900   256  miércoles
3        4    1  1900   257     jueves
4        5    1  1900   258    viernes
...    ...  ...   ...   ...        ...
73409   27   12  2100   170      lunes
73410   28   12  2100   171     martes
73411   29   12  2100   172  miércoles
73412   30   12  2100   173     jueves
73413   31   12  2100   174    viernes

[73414 rows x 5 columns]

In [13]:
X = df[['Día', 'Mes', 'Año']]
Y = df['Día_semana']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

modelo_bruto = LogisticRegression(max_iter=1000)
modelo_bruto.fit(x_train, y_train)

print("Acierto con datos en bruto:", modelo_bruto.score(x_test, y_test))

Acierto con datos en bruto: 0.13779795686719637

In [9]:
df['Seno'] = np.sin(2 * np.pi * df['Suma'] / 7)
df['Coseno'] = np.cos(2 * np.pi * df['Suma'] / 7)

In [14]:
X = df[['Seno', 'Coseno']]
Y = df['Día_semana']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

modelo = LogisticRegression(max_iter=1000)
modelo.fit(x_train, y_train)

print("Acierto con seno y coseno:", modelo.score(x_test, y_test))

Acierto con seno y coseno: 1.0

In [12]:
while True:
    try:
        dia = int(input("Día: "))
        mes = int(input("Mes: "))
        anio = int(input("Año: "))
        break
    except ValueError:
        print("Oops! No es válido. Intente nuevamente...")

suma, _ = zeller(dia, mes, anio)

X1 = pd.DataFrame([[np.sin(2 * np.pi * suma / 7), np.cos(2 * np.pi * suma / 7)]],
                  columns=['Seno', 'Coseno'])

resultado = modelo.predict(X1)
print("El", dia, "/", mes, "/", anio, "es", resultado[0])

KeyboardInterrupt: Interrupted by user